# Generated by Django 3.1.4 on 2021-01-26 07:32

import django.db.models.deletion
import django.utils.crypto
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitRepository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL', models.URLField(help_text='https://github.com/owner-name/repository-name.git', verbose_name='URL for the repository')),
                ('secret', models.CharField(default=django.utils.crypto.get_random_string, max_length=255, verbose_name='Secret for webhook')),
            ],
            options={
                'verbose_name_plural': 'Git repositories',
            },
        ),
        migrations.CreateModel(
            name='GitTextPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='git_md_page_gittextpluginmodel', serialize=False, to='cms.cmsplugin')),
                ('file', models.CharField(max_length=255, verbose_name='Full path to the file in the repository.')),
                ('content', models.TextField()),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='git_md_page.gitrepository')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
