# Generated by Django 3.1.4 on 2021-01-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git_md_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitrepository',
            name='branch',
            field=models.CharField(default='master', help_text='Source branch is usually either master or main.', max_length=63, verbose_name='Source branch'),
            preserve_default=False,
        ),
    ]
