# Generated by Django 4.2.6 on 2023-10-09 13:53

from django.db import migrations, models
import django.db.models.deletion
import git_md_page.models.git_plugins


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0022_auto_20180620_1551"),
        ("git_md_page", "0002_gitrepository_branch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gitrepository",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="gitrepository",
            name="secret",
            field=models.CharField(
                default=git_md_page.models.git_plugins.get_default_secret,
                max_length=255,
                verbose_name="Secret for webhook",
            ),
        ),
        migrations.AlterField(
            model_name="gittextpluginmodel",
            name="cmsplugin_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                related_name="%(app_label)s_%(class)s",
                serialize=False,
                to="cms.cmsplugin",
            ),
        ),
    ]
