# Generated by Django 4.2.6 on 2023-10-10 07:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.crypto
import functools


class Migration(migrations.Migration):

    dependencies = [
        ("git_md_page", "0002_gitrepository_branch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gitrepository",
            name="URL",
            field=models.URLField(
                help_text="https://github.com/owner-name/repository-name.git URL must be unique to this site.",
                unique=True,
                verbose_name="URL for the repository",
            ),
        ),
        migrations.AlterField(
            model_name="gitrepository",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="gitrepository",
            name="secret",
            field=models.CharField(
                default=functools.partial(django.utils.crypto.get_random_string, *(), **{"length": 12}),
                max_length=255,
                verbose_name="Secret for webhook",
            ),
        ),
        migrations.AlterField(
            model_name="gittextpluginmodel",
            name="cmsplugin_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                related_name="%(app_label)s_%(class)s",
                serialize=False,
                to="cms.cmsplugin",
            ),
        ),
    ]
